spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_cs_v01
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
      ru.friend.crm: debug
  pattern:
      console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
      file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: crm.log

server:
  port: 8052